<b> General Analysis </b>

#### Inspecting the Dataset `company_list`

In [2]:
%%sql

SELECT * FROM company_list LIMIT 5;

,id,sector,serial_number,symbol_link,symbol_text,symbol,symbol_1,company_link,company_text,company,listed_share,paid_up_rs,total_paid_up_capital_rs,market_capitalization_rs,date_of_operation,ltp,as_of
0,19ea4f39-6908-454b-b8a3-3e3afb419ab5,Commercial Bank,2,https://www.sharesansar.com/company/sbl,SBL,sbl,SBL,https://www.sharesansar.com/company/sbl,Siddhartha Bank Limited,Siddhartha Bank Limited,147944792,100,14794479200,4.774178e+10,2002-12-24,322.7,2025-11-19
1,6abcd3c7-4b48-4734-9e6e-57336b8020d4,Commercial Bank,3,https://www.sharesansar.com/company/kbl,KBL,kbl,KBL,https://www.sharesansar.com/company/kbl,Kumari Bank Limited,Kumari Bank Limited,262258613,100,26225861300,4.655090e+10,2001-04-03,177.5,2025-11-19
2,8847f9cb-1151-4f1e-af4c-dbda978aed86,Commercial Bank,4,https://www.sharesansar.com/company/mbl,MBL,mbl,MBL,https://www.sharesansar.com/company/mbl,Machhapuchchhre Bank Limited,Machhapuchchhre Bank Limited,120862116,100,12086211600,2.556234e+10,2012-07-09,211.5,2025-11-19
3,0cc8e566-5f65-4427-b63d-1ca4419b524c,Commercial Bank,5,https://www.sharesansar.com/company/ebl,EBL,ebl,EBL,https://www.sharesansar.com/company/ebl,Everest Bank Limited,Everest Bank Limited,137213760,100,13721376000,8.754238e+10,1994-10-18,638.0,2025-11-19
4,3bab68b5-ffb7-44f7-82f5-30afb9050173,Commercial Bank,6,https://www.sharesansar.com/company/sbi,SBI,sbi,SBI,https://www.sharesansar.com/company/sbi,Nepal SBI Bank Limited,Nepal SBI Bank Limited,108991581,100,10899158100,4.301898e+10,1993-07-07,394.7,2025-11-19

### Count of records in the `company_list` table

In [3]:
%%sql
SELECT COUNT(*) AS total_records_in_company_list FROM company_list;

   total_records_in_company_list
0                            615

### Inspecting the dataset `combined_price_history`

In [4]:
%%sql
SELECT * FROM combined_price_history LIMIT 5;

,id,symbol,company_name,sector,symbol_link,serial_number,date_added,unlocked,high,low,ltp,percent_change,qty,turnover
0,5ed30c36-cc5c-409a-83aa-d81f5918f23d,bbc,Bishal Bazar Company Limited,Trading,https://www.sharesansar.com/company/bbc,2174,1995-07-20,2220,2220,2220,2220,0,560,0
1,2144523f-0577-45a2-b600-5fc7b279aa8d,bbc,Bishal Bazar Company Limited,Trading,https://www.sharesansar.com/company/bbc,2173,1995-07-26,2220,2442,2442,2442,0,150,0
2,104f6015-8c4e-4c6f-9d66-a576e84bb04d,bbc,Bishal Bazar Company Limited,Trading,https://www.sharesansar.com/company/bbc,2172,1995-07-30,2442,2500,2500,2500,0,200,0
3,914d0a1a-9364-45fb-8210-a6b4836e5f9f,bbc,Bishal Bazar Company Limited,Trading,https://www.sharesansar.com/company/bbc,2171,1995-08-02,2500,2501,2501,2501,0,18,0
4,22bedc28-715d-4b6b-90bb-78017f9934d3,bbc,Bishal Bazar Company Limited,Trading,https://www.sharesansar.com/company/bbc,2170,1995-08-06,2501,2500,2500,2500,0,40,0

### Count of records in the `combined_price_history` table

In [5]:
%%sql
SELECT COUNT(*) AS total_records_in_company_price_history FROM combined_price_history;

   total_records_in_company_price_history
0                                  453814

### Time frame for `company_list`

In [11]:
%%sql
SELECT MIN(date_of_operation) AS data_from, MAX(date_of_operation) AS data_to FROM company_list;

    data_from     data_to
0  1937-11-15  2024-05-19

### Time frame for `combined_price_history`

In [12]:
%%sql
SELECT MIN(date_added) AS data_from, MAX(date_added) AS data_to FROM combined_price_history;

    data_from     data_to
0  1995-07-20  2025-11-20