### Which sector has the highest `market capitalization`

Side Note: Market capitalization, or market cap, is the total dollar value of a company’s outstanding shares of stock, calculated by multiplying the current share price by the total number of outstanding shares.

In [37]:
%%sql
SELECT
    SUM(market_capitalization_rs) AS net_market_capitalization_rs, sector
    FROM company_list
    GROUP BY sector
ORDER BY net_market_capitalization_rs DESC

    net_market_capitalization_rs                        sector
0                            NaN              Government Bonds
1                   9.850457e+11               Commercial Bank
2                   6.678779e+11                    Hydropower
3                   4.507150e+11                        Others
4                   3.964131e+11                Life Insurance
5                   3.643423e+11                  Microfinance
6                   3.253813e+11                    Investment
7                   2.531858e+11  Manufacturing and Processing
8                   2.141280e+11                       Trading
9                   2.101053e+11          Corporate Debentures
10                  2.028428e+11            Non-Life Insurance
11                  1.960619e+11              Development Bank
12                  1.379709e+11                Promoter Share
13                  1.277618e+11               Hotel & Tourism
14                  7.114158e+10                       Finance
15                  4.850838e+10                   Mutual Fund
16                  9.500000e+08              Preference Share

### `Government Bonds` are not a number, inspecting that little more.

In [26]:
%%sql
SELECT COUNT(*) as government_bound_counts
    FROM company_list
WHERE sector = 'Government Bonds'

   government_bound_counts
0                        2

### Company with the top 20 highest `market capitalization`

In [25]:
%%sql
SELECT SUM(market_capitalization_rs) as net_market_capitalization_rs, company
    FROM company_list
    WHERE market_capitalization_rs IS NOT NULL
    GROUP BY company
ORDER BY net_market_capitalization_rs DESC LIMIT 20;

,net_market_capitalization_rs,company
0,1.970755e+11,Bishal Bazar Company Limited
1,1.767702e+11,Nepal Reinsurance Company Limited
2,1.534140e+11,Nepal Doorsanchar Company Limited
3,1.371790e+11,Nabil Bank Limited
4,1.181616e+11,Citizen Investment Trust
5,1.072294e+11,10.25% Global IME Bank Limited Debenture 2080/81
6,8.754238e+10,Everest Bank Limited
7,8.629192e+10,Himalayan Reinsurance Limited
8,8.534139e+10,Global IME Bank Limited
9,7.213982e+10,Nepal Life Insurance Company Limited
10,6.557470e+10,Hydroelectricity Investment and Development Co...
11,6.484433e+10,Nepal Investment Mega Bank Limited
12,6.395984e+10,Standard Chartered Bank Nepal Limited
13,5.959440e+10,Nepal Infrastructure Bank Limited
14,5.611871e+10,Laxmi Sunrise Bank Limited
15,5.577327e+10,Soaltee Hotel Limited
16,4.885569e+10,Prime Commercial Bank Limited
17,4.774178e+10,Siddhartha Bank Limited
18,4.655090e+10,Kumari Bank Limited
19,4.653000e+10,Life Insurance Corporation Nepal Limited

### Sector with the highest `total_paid_up_capital_rs`

Side Note:- Total Paid-Up Capital (Rs) refers to the actual amount of money a company has received from its shareholders in exchange for shares of stock.

In [36]:
%%sql
SELECT
    MAX(total_paid_up_capital_rs) as total_paid_up_capital_rs_sector, sector
    FROM company_list
    WHERE total_paid_up_capital_rs IS NOT NULL
    GROUP BY sector
ORDER BY total_paid_up_capital_rs_sector DESC;

    total_paid_up_capital_rs_sector                        sector
0                      103105160000          Corporate Debentures
1                       38115852800               Commercial Bank
2                       24559813400                    Investment
3                       21180000000                    Hydropower
4                       18000000000                        Others
5                       11514672800                Promoter Share
6                        9143237400                Life Insurance
7                        8000388900              Development Bank
8                        5456808500  Manufacturing and Processing
9                        5000000000                   Mutual Fund
10                       4312621700                  Microfinance
11                       4010000000                       Trading
12                       3029334600            Non-Life Insurance
13                       3013200000               Hotel & Tourism
14                       1351552900                       Finance
15                        200000000              Preference Share

### Top 30 company with the highest `total_paid_up_capital_rs`

In [40]:
%%sql
SELECT
    MAX(total_paid_up_capital_rs) as total_paid_up_capital_rs_sector, company, sector
    FROM company_list
    WHERE total_paid_up_capital_rs IS NOT NULL
    GROUP BY company, sector
ORDER BY total_paid_up_capital_rs_sector DESC LIMIT 30;

,total_paid_up_capital_rs_sector,company,sector
0,103105160000,10.25% Global IME Bank Limited Debenture 2080/81,Corporate Debentures
1,38115852800,Global IME Bank Limited,Commercial Bank
2,34128594900,Nepal Investment Mega Bank Limited,Commercial Bank
3,27056998400,Nabil Bank Limited,Commercial Bank
4,26225861300,Kumari Bank Limited,Commercial Bank
5,24559813400,Hydroelectricity Investment and Development Co...,Investment
6,24346512300,Laxmi Sunrise Bank Limited,Commercial Bank
7,23542489900,Prabhu Bank Limited,Commercial Bank
8,21656615800,Himalayan Bank Limited,Commercial Bank
9,21600000000,Nepal Infrastructure Bank Limited,Investment
10,21180000000,Upper Tamakoshi Hydropower Limited,Hydropower
11,19402575900,Prime Commercial Bank Limited,Commercial Bank
12,18000000000,Nepal Doorsanchar Company Limited,Others
13,15507463800,Citizens Bank International Limited,Commercial Bank
14,14917567000,NIC Asia Bank Limited,Commercial Bank
15,14794479200,Siddhartha Bank Limited,Commercial Bank
16,14694023000,Nepal Bank Limited,Commercial Bank
17,13855224400,Agricultural Development Bank Limited,Commercial Bank
18,13721376000,Everest Bank Limited,Commercial Bank
19,13581525600,Sanima Bank Limited,Commercial Bank
20,13422187100,Nepal Reinsurance Company Limited,Others
21,12086211600,Machhapuchchhre Bank Limited,Commercial Bank
22,11514672800,Nepal Credit and Commerce Bank Limited Promote...,Promoter Share
23,10899158100,Nepal SBI Bank Limited,Commercial Bank
24,10868000000,Himalayan Reinsurance Limited,Others
25,10042368400,Standard Chartered Bank Nepal Limited,Commercial Bank
26,9143237400,Himalayan Life Insurance Limited,Life Insurance
27,9028763300,Nepal Life Insurance Company Limited,Life Insurance
28,8782397400,Chilime Hydro power Company Limited,Hydropower
29,8000388900,Muktinath Bikas Bank Limited,Development Bank