### Which sector has the highest `market capitalization`

Side Note: Market capitalization, or market cap, is the total dollar value of a company’s outstanding shares of stock, calculated by multiplying the current share price by the total number of outstanding shares.

In [54]:
%%sql
SELECT
    SUM(market_capitalization_rs) AS net_market_capitalization_rs, sector
    FROM company_list
    GROUP BY sector
ORDER BY net_market_capitalization_rs DESC

    net_market_capitalization_rs                        sector
0                            NaN              Government Bonds
1                   6.678779e+11                    Hydropower
2                   6.223126e+11               Commercial Bank
3                   4.507150e+11                        Others
4                   3.964131e+11                Life Insurance
5                   3.643423e+11                  Microfinance
6                   3.253813e+11                    Investment
7                   2.531858e+11  Manufacturing and Processing
8                   2.141280e+11                       Trading
9                   2.101053e+11          Corporate Debentures
10                  2.028428e+11            Non-Life Insurance
11                  1.960619e+11              Development Bank
12                  1.379709e+11                Promoter Share
13                  7.198857e+10               Hotel & Tourism
14                  6.560539e+10                       Finance
15                  4.850838e+10                   Mutual Fund
16                  9.500000e+08              Preference Share

### `Government Bonds` are not a number, inspecting that little more.

In [55]:
%%sql
SELECT COUNT(*) as government_bound_counts
    FROM company_list
WHERE sector = 'Government Bonds'

   government_bound_counts
0                        2

### Company with the top 20 highest `market capitalization`

In [56]:
%%sql
SELECT SUM(market_capitalization_rs) as net_market_capitalization_rs, company
    FROM company_list
    WHERE market_capitalization_rs IS NOT NULL
    GROUP BY company
ORDER BY net_market_capitalization_rs DESC LIMIT 20;

,net_market_capitalization_rs,company
0,1.970755e+11,Bishal Bazar Company Limited
1,1.767702e+11,Nepal Reinsurance Company Limited
2,1.534140e+11,Nepal Doorsanchar Company Limited
3,1.181616e+11,Citizen Investment Trust
4,1.072294e+11,10.25% Global IME Bank Limited Debenture 2080/81
5,8.754238e+10,Everest Bank Limited
6,8.629192e+10,Himalayan Reinsurance Limited
7,8.534139e+10,Global IME Bank Limited
8,7.213982e+10,Nepal Life Insurance Company Limited
9,6.557470e+10,Hydroelectricity Investment and Development Co...
10,6.484433e+10,Nepal Investment Mega Bank Limited
11,5.959440e+10,Nepal Infrastructure Bank Limited
12,5.611871e+10,Laxmi Sunrise Bank Limited
13,4.885569e+10,Prime Commercial Bank Limited
14,4.774178e+10,Siddhartha Bank Limited
15,4.655090e+10,Kumari Bank Limited
16,4.653000e+10,Life Insurance Corporation Nepal Limited
17,4.578201e+10,NIC Asia Bank Limited
18,4.477950e+10,Sarbottam Cement Limited
19,4.364778e+10,Prabhu Bank Limited

### Sector with the highest `total_paid_up_capital_rs`

Side Note:- Total Paid-Up Capital (Rs) refers to the actual amount of money a company has received from its shareholders in exchange for shares of stock.

In [34]:
%%sql
SELECT
    SUM(total_paid_up_capital_rs) as total_paid_up_capital_rs_sector, sector
    FROM company_list
    WHERE total_paid_up_capital_rs IS NOT NULL
    GROUP BY sector
ORDER BY total_paid_up_capital_rs_sector DESC;

    total_paid_up_capital_rs_sector                        sector
0                      250370510300               Commercial Bank
1                      177975836000          Corporate Debentures
2                      177076667000                    Hydropower
3                       71103965600                Life Insurance
4                       57101319300                    Investment
5                       51385839580                   Mutual Fund
6                       46746115300                        Others
7                       44612601500              Development Bank
8                       43438202900                Promoter Share
9                       38361102700                  Microfinance
10                      28864706400            Non-Life Insurance
11                      23889241000  Manufacturing and Processing
12                      14315377900                       Finance
13                      11123906200               Hotel & Tourism
14                       4330717100                       Trading
15                        200000000              Preference Share

### Top 30 company with the highest `total_paid_up_capital_rs`

In [58]:
%%sql
SELECT
    MAX(total_paid_up_capital_rs) as total_paid_up_capital_rs_sector, company, sector
    FROM company_list
    WHERE total_paid_up_capital_rs IS NOT NULL
    GROUP BY company, sector
ORDER BY total_paid_up_capital_rs_sector DESC LIMIT 30;

,total_paid_up_capital_rs_sector,company,sector
0,103105160000,10.25% Global IME Bank Limited Debenture 2080/81,Corporate Debentures
1,38115852800,Global IME Bank Limited,Commercial Bank
2,34128594900,Nepal Investment Mega Bank Limited,Commercial Bank
3,26225861300,Kumari Bank Limited,Commercial Bank
4,24559813400,Hydroelectricity Investment and Development Co...,Investment
5,24346512300,Laxmi Sunrise Bank Limited,Commercial Bank
6,23542489900,Prabhu Bank Limited,Commercial Bank
7,21600000000,Nepal Infrastructure Bank Limited,Investment
8,21180000000,Upper Tamakoshi Hydropower Limited,Hydropower
9,19402575900,Prime Commercial Bank Limited,Commercial Bank
10,18000000000,Nepal Doorsanchar Company Limited,Others
11,15507463800,Citizens Bank International Limited,Commercial Bank
12,14917567000,NIC Asia Bank Limited,Commercial Bank
13,14794479200,Siddhartha Bank Limited,Commercial Bank
14,13721376000,Everest Bank Limited,Commercial Bank
15,13581525600,Sanima Bank Limited,Commercial Bank
16,13422187100,Nepal Reinsurance Company Limited,Others
17,12086211600,Machhapuchchhre Bank Limited,Commercial Bank
18,11514672800,Nepal Credit and Commerce Bank Limited Promote...,Promoter Share
19,10868000000,Himalayan Reinsurance Limited,Others
20,9143237400,Himalayan Life Insurance Limited,Life Insurance
21,9028763300,Nepal Life Insurance Company Limited,Life Insurance
22,8782397400,Chilime Hydro power Company Limited,Hydropower
23,8000388900,Muktinath Bikas Bank Limited,Development Bank
24,6842100000,Rasuwagadhi Hydropower Company Limited,Hydropower
25,6481712500,Citizen Investment Trust,Investment
26,6075927800,Api Power Company Limited,Hydropower
27,6021348600,Garima Bikas Bank Limited,Development Bank
28,6000000000,Madhya Bhotekoshi Jalavidyut Company Limited,Hydropower
29,5500000000,Life Insurance Corporation Nepal Limited,Life Insurance

### LET'S CHECK FOR THE DATA FROM THE YEAR LESS THAN 1994 (Official trading floor opened in 1994)

We need to drop the data.

In [59]:
%%sql
SELECT date_of_operation, company
    FROM company_list
    WHERE date_of_operation < '1994-01-01'
ORDER BY date_of_operation ASC;

Empty DataFrame
Columns: [date_of_operation, company]
Index: []

In [ ]:
%%sql
DELETE FROM company_list WHERE date_of_operation < '1994-01-13'

### Check the minimum date of operation just to be sure.

In [13]:
%%sql
SELECT date_of_operation, company, sector
    FROM company_list
ORDER BY date_of_operation ASC
LIMIT 5;

  date_of_operation                                   company           sector
0        1994-10-18                      Everest Bank Limited  Commercial Bank
1        1995-05-15          Goodwill Finance Company Limited          Finance
2        1995-06-01  Shree Investment Finance Company Limited          Finance
3        1996-02-01              Best Finance Company Limited          Finance
4        1996-02-26               Progressive Finance Limited          Finance

### Highest listest share of a company

In [33]:
%%sql
SELECT company, sector, listed_share
    FROM company_list
    WHERE listed_share IS NOT NULL
    ORDER BY listed_share DESC
LIMIT 20;

,company,sector,listed_share
0,HLI Large Cap Fund,Mutual Fund,500000000
1,Global IME Bank Limited,Commercial Bank,381158528
2,Nepal Investment Mega Bank Limited,Commercial Bank,341285949
3,Kumari Bank Limited,Commercial Bank,262258613
4,Hydroelectricity Investment and Development Co...,Investment,245598134
5,Laxmi Sunrise Bank Limited,Commercial Bank,243465123
6,Prabhu Bank Limited,Commercial Bank,235424899
7,Nepal Infrastructure Bank Limited,Investment,216000000
8,Upper Tamakoshi Hydropower Limited,Hydropower,211800000
9,Prime Commercial Bank Limited,Commercial Bank,194025759
10,Nepal Doorsanchar Company Limited,Others,180000000
11,Citizens Bank International Limited,Commercial Bank,155074638
12,Siddhartha Equity Fund,Mutual Fund,150000000
13,Global IME Samunnat Yojana -II,Mutual Fund,150000000
14,NIBL Samriddhi Fund - 2,Mutual Fund,150000000
15,NIC Asia Bank Limited,Commercial Bank,149175670
16,Siddhartha Bank Limited,Commercial Bank,147944792
17,Everest Bank Limited,Commercial Bank,137213760
18,Sanima Bank Limited,Commercial Bank,135815256
19,Nepal Reinsurance Company Limited,Others,134221871