### Which sector has the highest `market capitalization`

Side Note: Market capitalization, or market cap, is the total dollar value of a company’s outstanding shares of stock, calculated by multiplying the current share price by the total number of outstanding shares.

In [11]:
%%sql
SELECT
    SUM(market_capitalization_rs) AS net_market_capitalization_rs, sector
    FROM company_list
    GROUP BY sector
ORDER BY net_market_capitalization_rs DESC

    net_market_capitalization_rs                        sector
0                            NaN              Government Bonds
1                   9.850457e+11               Commercial Bank
2                   6.678779e+11                    Hydropower
3                   4.507150e+11                        Others
4                   3.964131e+11                Life Insurance
5                   3.643423e+11                  Microfinance
6                   3.253813e+11                    Investment
7                   2.531858e+11  Manufacturing and Processing
8                   2.141280e+11                       Trading
9                   2.101053e+11          Corporate Debentures
10                  2.028428e+11            Non-Life Insurance
11                  1.960619e+11              Development Bank
12                  1.379709e+11                Promoter Share
13                  1.277618e+11               Hotel & Tourism
14                  7.114158e+10                       Finance
15                  4.850838e+10                   Mutual Fund
16                  9.500000e+08              Preference Share

### `Government Bonds` are not a number, inspecting that little more.

In [15]:
%%sql
SELECT COUNT(*)
    FROM company_list
WHERE sector = 'Government Bonds'

   count
0      2

### Company with the highest `market capitalization`

In [24]:
%%sql
SELECT SUM(market_capitalization_rs) as net_market_capitalization_rs, company
    FROM company_list
    WHERE market_capitalization_rs IS NOT NULL
    GROUP BY company
ORDER BY net_market_capitalization_rs DESC;

,net_market_capitalization_rs,company
0,1.970755e+11,Bishal Bazar Company Limited
1,1.767702e+11,Nepal Reinsurance Company Limited
2,1.534140e+11,Nepal Doorsanchar Company Limited
3,1.371790e+11,Nabil Bank Limited
4,1.181616e+11,Citizen Investment Trust
...,...,...
492,1.000000e+06,Union Finance Company Limited Promoter Share
493,0.000000e+00,NDEP Development Bank Limited Promoter Share
494,0.000000e+00,Vibor Bikas Bank Limited Promoter Share
495,0.000000e+00,Alliance Insurance Company Limited Promoter
496,0.000000e+00,Prudential Finance Company Limited Promoter share